"""
═══════════════════════════════════════════════════════════════
SESSION MODELS — Chat Session Context Preservation
═══════════════════════════════════════════════════════════════
Models for tracking the full conversational context across
all stages: initial Q1-Q3, dynamic persona questions, and
tool recommendations.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class SessionStage(str, Enum):
    """Current stage of the user's session flow."""
    OUTCOME = "outcome"           # Q1: Growth bucket selection
    DOMAIN = "domain"             # Q2: Sub-category / domain selection
    TASK = "task"                 # Q3: Task selection
    URL_INPUT = "url_input"       # Business URL collection (after early recs)
    SCALE_QUESTIONS = "scale_questions"      # Business scale/context classification
    DYNAMIC_QUESTIONS = "dynamic_questions"  # AI-generated follow-up questions
    RECOMMENDATION = "recommendation"       # Final tool recommendation
    COMPLETE = "complete"


class QuestionAnswer(BaseModel):
    """A single question-answer pair."""
    question: str
    answer: str
    question_type: str = "static"  # "static" for Q1-Q3, "dynamic" for AI-generated


class SessionContext(BaseModel):
    """
    Full session context preserved across the chat flow.
    Tracks every Q&A, persona loaded, and recommendations given.
    """
    session_id: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Current stage
    stage: SessionStage = SessionStage.OUTCOME

    # Q1: Outcome / Growth Bucket
    outcome: Optional[str] = None
    outcome_label: Optional[str] = None

    # Q2: Domain / Sub-Category
    domain: Optional[str] = None

    # Q3: Task
    task: Optional[str] = None

    # Persona doc loaded for this domain
    persona_doc_name: Optional[str] = None
    persona_context_loaded: bool = False

    # All Q&A pairs (static + dynamic)
    questions_answers: list[QuestionAnswer] = []

    # Dynamic questions generated by the AI agent
    dynamic_questions: list[str] = []
    dynamic_questions_asked: int = 0
    dynamic_questions_total: int = 0

    # Claude RCA diagnostic state
    rca_diagnostic_context: dict[str, Any] = {}   # Raw dynamic-loader output (problems, rca_bridge, etc.)
    rca_history: list[dict[str, str]] = []         # [{"question": ..., "answer": ...}, ...]
    rca_complete: bool = False                     # True when Claude signals "complete"
    rca_summary: str = ""                          # Claude's summary when done
    rca_fallback_active: bool = False              # True if Claude failed and static Qs are used

    # Early recommendations (after Q3, before full RCA)
    early_recommendations: list[dict[str, Any]] = []   # Tools recommended based on Q1+Q2+Q3 only
    early_recommendations_message: str = ""             # Encouragement message to continue RCA

    # Website & audience insights
    website_url: Optional[str] = None                   # Business website URL
    url_submitted_at: Optional[str] = None              # ISO timestamp of URL submission
    url_type: Optional[str] = None                      # "website" or "social_profile"
    audience_insights: dict[str, Any] = {}              # {intended_audience, actual_audience, mismatch_analysis, recommendations}

    # Crawl data (populated asynchronously after URL submission)
    crawl_raw: dict[str, Any] = {}                      # Raw crawl output: homepage, pages_crawled, tech_signals, etc.
    crawl_summary: dict[str, Any] = {}                  # Compressed summary: points, crawl_status, completed_at
    crawl_status: str = ""                              # "in_progress", "complete", "failed", or empty

    # Business scale / profile (populated from Scale Questions)
    business_profile: dict[str, Any] = {}               # {team_size, revenue_range, business_stage, ...}
    scale_questions_complete: bool = False               # True when all scale Qs answered

    # Recommended tools
    recommended_extensions: list[dict[str, Any]] = []
    recommended_gpts: list[dict[str, Any]] = []
    recommended_companies: list[dict[str, Any]] = []

    # Free-form conversation history for the AI agent
    agent_conversation: list[dict[str, str]] = []


# ── API Request/Response Models ────────────────────────────────


class GenerateDynamicQuestionsRequest(BaseModel):
    """Request to generate dynamic follow-up questions after Q1-Q3."""
    session_id: str
    outcome: str
    outcome_label: str
    domain: str
    task: str


class DynamicQuestion(BaseModel):
    """A question with options — loaded directly from persona documents."""
    question: str
    options: list[str] = []
    allows_free_text: bool = True
    section: str = ""         # problems, rca_bridge, opportunities
    section_label: str = ""   # Human-readable label
    insight: str = ""         # Knowledge-embedded teaching nugget (stat, benchmark, pattern)


class GenerateDynamicQuestionsResponse(BaseModel):
    """Response containing AI-generated dynamic questions."""
    session_id: str
    questions: list[DynamicQuestion]
    persona_loaded: str


class SubmitDynamicAnswerRequest(BaseModel):
    """Request to submit an answer to a dynamic question."""
    session_id: str
    question_index: int
    answer: str


class SubmitDynamicAnswerResponse(BaseModel):
    """Response after submitting a dynamic answer."""
    session_id: str
    next_question: Optional[DynamicQuestion] = None
    all_answered: bool = False
    rca_mode: bool = False           # True = Claude adaptive mode
    acknowledgment: str = ""         # Claude's brief acknowledgment of the answer
    rca_summary: str = ""            # Claude's summary when diagnostic is complete
    insight: str = ""                # Teaching insight for the next question


class GetRecommendationsRequest(BaseModel):
    """Request to get final tool recommendations based on all answers."""
    session_id: str


class ToolRecommendation(BaseModel):
    """A single tool recommendation."""
    name: str
    description: str
    url: Optional[str] = None
    category: str  # 'extension', 'gpt', 'company'
    free: Optional[bool] = None
    rating: Optional[str] = None
    why_recommended: str = ""
    implementation_stage: str = ""   # When in their workflow to implement (e.g., "Day 1 — Immediate", "Week 2 — After auditing current process")
    issue_solved: str = ""           # What specific problem from RCA this tool addresses
    ease_of_use: str = ""            # How easy to adopt with current process (e.g., "Plug & play — no learning curve", "30-min setup, works with your existing tools")


class GetRecommendationsResponse(BaseModel):
    """Final recommendations response with full session context."""
    session_id: str
    extensions: list[ToolRecommendation] = []
    gpts: list[ToolRecommendation] = []
    companies: list[ToolRecommendation] = []
    summary: str = ""
    session_context: dict[str, Any] = {}
